######################################################################
# Automatically generated by qmake (3.0) Fri Sep 15 12:26:38 2017
######################################################################
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

greaterThan(QT_MAJOR_VERSION, 4): QT += widget
TEMPLATE = app
TARGET = peerster
INCLUDEPATH += .
DEPENDPATH += .
<<<<<<< HEAD
=======
QMAKE_CXXFLAGS += -std=c++0x
>>>>>>> 22a69bc06f5d3d1797adac9982106bef18b3fae7
QT += network core gui

QMAKE_CXXFLAGS += -std=c++0x
# Input
HEADERS += chatdialog.h netsocket.h peer.h textinput.h \
    control.h \
    model.h \
    lib.h
SOURCES += chatdialog.cpp main.cc netsocket.cpp peer.cpp textinput.cpp \
    control.cpp \
    model.cpp
