######################################################################
# Automatically generated by qmake (3.0) Fri Sep 15 12:26:38 2017
######################################################################

TEMPLATE = app
TARGET = peerster
INCLUDEPATH += .
DEPENDPATH += .
QT += network
QT += widgets

# Input
HEADERS += chatdialog.h netsocket.h peer.h textinput.h
SOURCES += chatdialog.cpp main.cc netsocket.cpp peer.cpp textinput.cpp
